REPROSEC/dolev-yao-star-extrinsic

- examples/nsl_pk/DY.Example.NSL.Debug.Printing.fst
- src/lib/utils/DY.Lib.Printing.fst
Although we can only merge a pull request when the CI succeeds on the pull-request, the GitHub interface allowed me to push buttons in a way that we have a red commit on the main branch…
It happened because latest commit of `main` (hence #4) was not merged in #16, and although the latest commit of #16 did pass the CI checks, the merge of #4 and #16 was not passing the CI checks.
This pull-request fixes the CI and finish the work of #16 in the files added by #4. I will see if one of the branch protection rules would have prevented this, or if we should have the discipline of merging main in the pull-request before merging the pull-request in main.
> fix: fix CI and finish #16 in the Printing modules

- src/lib/utils/DY.Lib.SplitPredicate.fst
Fixing https://github.com/REPROSEC/dolev-yao-star-extrinsic/issues/12.
I also re-ordered the record fields of `split_predicate_input_values` to match the order in the 2 instance definitions ([State.Tagged](https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/452210f88ac1180710f93ebecbb6394e38b970fa/src/lib/state/DY.Lib.State.Tagged.fst#L43) and [Event.Typed](https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/452210f88ac1180710f93ebecbb6394e38b970fa/src/lib/event/DY.Lib.Event.Typed.fst#L44)).
> Clarifying documentation for the split predicate method + reorder input_values fields

- CONTRIBUTING.md
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.fst
- src/lib/state/DY.Lib.State.Map.fst
- src/lib/state/DY.Lib.State.Tagged.fst
Fixing https://github.com/REPROSEC/dolev-yao-star-extrinsic/issues/20.
I also changed some names in the NSL example, so that it is more consistent. (Basically, moving the `nsl_` prefixes to the end).
For example: with the new typeclass naming convention we have `crypto_invariants_nsl` but the corresponding `nsl_trace_invariants` are not a typeclass instance. Still I renamed the latter to match the `crypto_invariants`.
The only places where `nsl_` is left as prefix are: `nsl_session`, `nsl_event` and `nsl_global_sess_ids`, for which I think this is ok.
> Unify typeclass instance names

- src/core/DY.Core.Trace.Type.fst
I needed the lemma `prefix_prefix_eq` for MLS*, and the lemma `prefix_prefix_grows` is borrowed from the branch `label_before`.
The lemma `prefix_prefix_eq` is useful to reason on things that happened before some time, e.g. `is_publishable (prefix tr time) b`. It ensures that when `tr` grows, the prefix stays the same hence the property stays true.
> feat: add lemmas on `prefix`

- examples/nsl_pk/DY.Example.NSL.Debug.Printing.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.fst
- examples/nsl_pk/DY.Example.NSL.SecurityProperties.fst
- src/core/DY.Core.Attacker.Knowledge.fst
- src/core/DY.Core.Label.Type.fst
- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Invariant.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/core/DY.Core.Trace.Type.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/state/DY.Lib.State.Map.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
- src/lib/state/DY.Lib.State.Tagged.fst
- src/lib/state/DY.Lib.State.Typed.fst
- src/lib/utils/DY.Lib.Printing.fst
Fixing https://github.com/REPROSEC/dolev-yao-star-extrinsic/issues/6: renamed occurrences of "state" and "session" to "version" and added a comment explaining the state model. 
There are no actual changes to the implementation. In particular, there is no new version id. The current version is just the latest `SetVersion` entry on the trace. I think, that matches what we previously had: There could have been several `SetState` entries with the same session id and only the last one was relevant.
Predicates/invariants are still called "state_predicate", since we are about to change some of those to support invariants for sessions and full states in the context of https://github.com/REPROSEC/dolev-yao-star-extrinsic/issues/9.
One thing left to discuss is corruption/attacker knowledge. …
> Some cleanup on states/session/version and types for session id and timestamp

- src/lib/comparse/DY.Lib.Comparse.Parsers.fst
Followup for #32, I realized when updating MLS* with the latest DY* that `state_id` did not have a corresponding message format, which is handy when you want to have a state that contain other state identifiers.
> fix: add message format for `state_id`

- .fst.config.json
- Makefile
- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- flake.lock
- src/lib/DY.Lib.fst
- src/lib/crypto/DY.Lib.Crypto.AEAD.Split.fst
- src/lib/crypto/DY.Lib.Crypto.KdfExpand.Split.fst
- src/lib/crypto/DY.Lib.Crypto.PkEncryption.Split.fst
- src/lib/crypto/DY.Lib.Crypto.Signature.Split.fst
- src/lib/crypto/DY.Lib.Crypto.SplitPredicate.fst
- src/lib/state/DY.Lib.State.Tagged.fst
Everything is in the title, this will allow to define cryptographic invariants modularly.
I tackled every cryptographic invariant that fits nicely in this framework, in particular, I left DH and KDF.Extract for future work.
The diff is big because this PR is based on the merge of #35 and #41, only the last commit is relevant (until we merge the two aforementioned PRs)
> feat: apply split function methodology to cryptographic invariants

- src/lib/crypto/DY.Lib.Crypto.AEAD.Split.fst
- src/lib/crypto/DY.Lib.Crypto.KdfExpand.Split.fst
- src/lib/crypto/DY.Lib.Crypto.PkEncryption.Split.fst
- src/lib/crypto/DY.Lib.Crypto.Signature.Split.fst
- src/lib/crypto/DY.Lib.Crypto.SplitPredicate.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/state/DY.Lib.State.Tagged.fst
- src/lib/utils/DY.Lib.SplitFunction.fst
While using the new split cryptographic predicate modules, I realized I could not use the `has_..._predicate` predicates easily. I think this is because when it is unfolded into `has_local_fun`, the `forall` quantifies on a complex type (e.g. `trace & (key:bytes{AeadKey? (get_usage key)}) & (bytes & bytes & bytes)` which is a tuple containing a refined type).
(If you a glimpse of the struggle this `forall` is, have a look at the `intro_has_..._predicate` proofs that aren't as trivial as they should be.)
This pull-request modifies these predicate to have more SMT-friendly quantification, and additionally, use a forall-pattern that acts like the well-known `SMTPat` on `Lemma`s. It's better proof-engineering because otherwise the `forall` is triggered on every instances of the type that is …
> fix: make `has_..._predicate` SMT-friendly

- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- src/core/DY.Core.Bytes.fst
- src/core/DY.Core.Trace.Invariant.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/lib/crypto/DY.Lib.Crypto.AEAD.Split.fst
- src/lib/crypto/DY.Lib.Crypto.KdfExpand.Split.fst
- src/lib/crypto/DY.Lib.Crypto.PkEncryption.Split.fst
- src/lib/crypto/DY.Lib.Crypto.Signature.Split.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/hpke/DY.Lib.HPKE.Lemmas.fst
- src/lib/hpke/DY.Lib.HPKE.Split.fst
- src/lib/state/DY.Lib.State.Map.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
- src/lib/state/DY.Lib.State.Tagged.fst
- src/lib/state/DY.Lib.State.Typed.fst
As proposed in #46, this PR use the typeclass mechanism more systematically for invariants.
The idea is that everywhere in the code there should only be one global invariant in the scope:
- either it is defined somewhere in the global scope, as it is done e.g. in the NSL or ISO-DH examples
- or it is a parameter of security proofs, as it is done in most of `DY.Lib`
It means that instead of typing these arguments by hand, we can let the typeclass resolution algorithm do that for us because there is only one possibility.
> cleanup: use typeclass mechanism systematically for invariants

- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/iso_dh/DY.Example.DH.SecurityProperties.fst
I noticed that in the authentication theorems of ISO-DH we only need to talk about corruption of signature keys of the other party, the attacker cannot use corrupted DH private keys to break authentication (unlike NSL where corrupting a nonce can be used to break authentication).
> fix: strengthen the authentication theorems of ISO-DH

- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- src/core/DY.Core.Attacker.Knowledge.fst
- src/core/DY.Core.Bytes.Type.fst
- src/core/DY.Core.Bytes.fst
- src/core/DY.Core.Label.Derived.fst
- src/core/DY.Core.Label.Type.fst
- src/core/DY.Core.Label.Unknown.fst
- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Base.fst
- src/core/DY.Core.Trace.Invariant.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/core/DY.Core.Trace.Type.fst
- src/core/DY.Core.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/utils/DY.Lib.Printing.fst
This PR builds on #54.
The previous label construction works with the duo `label` / `is_corrupt`, where `is_corrupt` is a predicate on a trace stating whether a given label was corrupt, and `label` is an AST that represent a subset of such trace predicates.
Before #54, we used the fact that `label` is an AST to ensure it has decidable equality (hence `bytes` also has decidable equality), so we were stuck in the subset of corruption predicates that could be expressed using this AST.
This PR generalize labels, by saying labels are corruption predicates in their full generality, so roughly `type label = trace -> prop`.
In particular, it subsumes the previous attempts at adding new features to labels, such as branch [`label_before`](https://github.com/REPROSEC/dolev-yao-star-extrinsic/compare/ …
> feat: generalize labels to be predicates

- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/iso_dh/DY.Example.DH.SecurityProperties.fst
- src/core/DY.Core.Bytes.fst
- src/core/DY.Core.Label.Derived.fst
- src/core/DY.Core.Label.Type.fst
- src/core/DY.Core.Label.Unknown.fst
- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Base.fst
Builds on #55.
Here, we exploit the fact that labels are predicate to use extensionality, meaning that if two labels are always equivalent (i.e. always flow in both directions, or that their corruption predicates are always equivalent), then they are equal.
We further use that to prove that `join` is commutative, or that `public` is an absorber for `join` (among other things). This leads to nicer theorems for the label of `dh`, where we can actually have label equality instead of the previous `always_equivalent`.
In turn this allows to use `==` instead of `equivalent tr` in the ISO-DH example, thereby simplifying its proof.
> feat: make labels extensional

- flake.lock
- src/core/DY.Core.Bytes.fst
- src/lib/hpke/DY.Lib.HPKE.Lemmas.fst
It looks like after FStarLang/FStar#3505 we need to bump a few rlimits.
With this PR, DY* compiles with the latest version of F*.
This type of PR is boring, should we enforce doing a review on it or can we decide on merging without review (once the CI is green)?
> chore: update F*

- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Base.fst
Discussed with @qaphla in the review of https://github.com/REPROSEC/dolev-yao-star-extrinsic/pull/73#discussion_r1799725191 .
> cleanup: rename `forget_label` to `replace_label`

- examples/iso_dh/DY.Example.DH.Debug.fst
- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/iso_dh/DY.Example.DH.Protocol.Stateful.fst
- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Debug.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
- src/lib/utils/DY.Lib.Printing.fst
Slight cleanup for a follow-up PR (in the spirit of "make the change easy, then make the easy change"), although I believe it is good in itself.
This is merging some parts of `PKI` and `PrivateKeys`:
- `public_key_type` and `private_key_type` are now the same type
- `public_key_type` are now prefixed with `LongTerm` so that the name are clearly different than the constructors of `usage` (it was the case before, but only because of bad conventions e.g. `Sig` vs `Sign`)
- `PrivateKeys` is now computing the key to install in the `PKI` of other principals. This is the change that motivates this PR, because otherwise the debug code has to call `pk` or `vk` by hand, and prove the `is_public_key_for` precondition of PKI using the `is_private_key_for` post-condition of PrivateKeys.
- in the NSL …
> cleanup: make PKI more aware of PrivateKeys

- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- src/core/DY.Core.Label.fst
- src/lib/comparse/DY.Lib.Comparse.Glue.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
Builds on #65.
In many proofs, we rely on the injectivity of `principal_label`, via the pattern
```fstar
pred = (fun tr pk msg ->
exists prin. get_sk_label pk == principal_label prin /\
... // something that involves `prin`
);
```
Because of the injectivity of `principal_label` if we know that `get_sk_label pk == principal_label "Alice"`, then we can use the predicate above with `prin == "Alice"`. This is done in both NSL and ISO-DH.
I now believe that this is more a hack than an actual feature: the labels are used to prove that two keys are distinct (the private key of Alice and the private key of Bob), whereas the goal of labels is initially to prove secrecy.
Proving that two keys are distinct is the role of usages: we already use them to prove that two keys in distinct protocols are …
> cleanup: stop relying on label injectivity

- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Base.fst
- src/lib/event/DY.Lib.Event.Typed.fst
This is useful when defining new labels, to prove the `is_corrupt_later` lemma.
While I was at it, I added some useful lemmas about `fmap_trace`, and a function that find a protocol event in the trace (handy when debugging a proof and transform a `event_triggered` into a `event_triggered_at` without having to `eliminate exists. …`).
> cleanup: make more predicates agnostic on label type

- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/iso_dh/DY.Example.DH.Protocol.Stateful.fst
- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/iso_dh/DY.Example.DH.SecurityProperties.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.SecurityProperties.fst
- src/core/DY.Core.Attacker.Knowledge.fst
- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Base.fst
- src/core/DY.Core.Trace.Invariant.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/core/DY.Core.Trace.Type.fst
- src/lib/state/DY.Lib.State.Map.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
- src/lib/state/DY.Lib.State.Tagged.fst
- src/lib/state/DY.Lib.State.Typed.fst
- src/lib/utils/DY.Lib.Printing.fst
- src/lib/utils/DY.Lib.SplitFunction.fst
This PR builds on #56 and #59.
Although I found how to have a nice diff in GitHub when a PR depends on another, I don't know how to do when it depends on two others, so the diff will have a combination of #59 and #60 (this PR). Hopefully it's not too bad because #59 is a small change.
To explain what this PR does, first a small refresher on labels (or at least, on one way to understand labels): the label associated with a `bytes` is a restriction on where this `bytes` can be stored, or more generally, on the data that could be used to derive this `bytes`. For example:
- `get_label buf == principal_label "Alice"` means `buf` may only be stored by Alice, and may only be encrypted to keys that can only be stored by Alice, etc
- `get_label buf == principal_state_label "Alice" 4` means `buf` …
> feat: introduce content-aware labels

- examples/iso_dh/DY.Example.DH.Debug.Proof.fst
- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/iso_dh/DY.Example.DH.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- src/core/DY.Core.Bytes.Type.fst
- src/core/DY.Core.Bytes.fst
- src/core/DY.Core.Trace.Base.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/lib/crypto/DY.Lib.Crypto.AEAD.Split.fst
- src/lib/crypto/DY.Lib.Crypto.PkEncryption.Split.fst
- src/lib/crypto/DY.Lib.Crypto.Signature.Split.fst
- src/lib/crypto/DY.Lib.Crypto.SplitPredicate.fst
- src/lib/hpke/DY.Lib.HPKE.Lemmas.fst
- src/lib/hpke/DY.Lib.HPKE.Split.fst
- src/lib/utils/DY.Lib.Printing.fst
Builds on #66.
When doing proofs on protocols more complex than NSL or ISO-DH, I noticed that it was annoying to do proofs with `get_usage`, because we rarely are 100% certain that `get_usage key == …`. However, in what I've seen, we can always prove `get_usage key == … \/ is_publishable tr key` (more on that below).
Hence, this PR introduces
```fstar
// used as: key `has_usage tr` usg
let has_usage tr key usg =
get_usage key == usg \/
(get_label tr key) `can_flow tr` public
```
and use it systematically in the pre and post-conditions to prove `bytes_invariant`.
I think that contrary to `get_usage key == …`, we can always prove `has_usage tr key usg` on a key:
- if `key` was encrypted using public-key encryption:
- if `key` is encrypted by a honest principal that knows `has_usage tr key …
> feat: introduce `has_usage` to improve bytes invariant

- examples/nsl_pk/DY.Example.NSL.Protocol.Total.Proof.fst
- examples/nsl_pk/DY.Example.NSL.SecurityProperties.fst
- src/core/DY.Core.Bytes.fst
- src/core/DY.Core.Label.Derived.fst
- src/core/DY.Core.Label.fst
Fixes #77 .
Now `flow_to_public_eq` triggers when in the context appears `is_corrupt tr l`, instead of ``l `can_flow tr` public``. It works better in the examples, but in DY.Core.Label, when proving things about what happens when labels flows to public, we need to call this lemma by hand for some reason I have not figured out. If that's a problem, we can later change it to an `SMTPatOr`, I guess. I prefer the SMT patterns working well in the examples but less well in the DY* internals.
> cleanup: rework label SMT patterns

- src/core/DY.Core.Trace.Base.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/state/DY.Lib.State.Map.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
- src/lib/state/DY.Lib.State.Tagged.fst
- src/lib/state/DY.Lib.State.Typed.fst
Fixing https://github.com/REPROSEC/dolev-yao-star-extrinsic/issues/80.
I also added "get_state => state_was_set" Lemmas (core, tagged, typed), which are often useful.
(For this, I needed the `last_entry_exists` Lemma in `Trace.Base`)
> Splitting `_invariant` Lemmas

- src/core/DY.Core.Bytes.fst
The combination of these two lemmas is stronger than `is_publishable`:
- before we only knew ``get_label tr … `can_flow tr` public``
- now we know `get_label tr … == public`
This is useful in MLS.
> cleanup: split `bytes_invariant` and `get_label` lemmas for `literal_to_bytes`

- differences_with_intrinsic.md
- examples/iso_dh/DY.Example.DH.Debug.Proof.fst
- src/core/DY.Core.Bytes.fst
- src/core/DY.Core.Label.Type.fst
- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Base.fst
- src/core/DY.Core.Trace.Invariant.fst
- src/core/DY.Core.Trace.Manipulation.fst
- src/core/DY.Core.Trace.Type.fst
- src/core/DY.Core.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/utils/DY.Lib.Printing.fst
Fixing https://github.com/REPROSEC/dolev-yao-star-extrinsic/issues/74 by renaming `trace_event` to `trace_entry` and related occurrences of `event` in functions and lemmas.
I hope, I didn't miss anything.
> Cleanup: Renamed `trace_event` to `trace_entry`

- src/core/DY.Core.Attacker.Knowledge.fst
- src/core/DY.Core.Label.fst
- src/core/DY.Core.Trace.Invariant.fst
- src/lib/event/DY.Lib.Event.Typed.fst
Some small clean-ups. 
1. Corrected a couple of typos.
2. Changed an ordering of a conjunction in a requires to match the other lemmas in the same file. 
3. Changed some indentation to clarify the return type.
> cleanup: correct small typos and small consistency tweaks

- src/core/DY.Core.Trace.Base.fst
Small cleanup to add some missing val declarations in DY.Core.Trace.Base to maintain codebase style.
> cleanup: add missing val statements to maintain style

- src/lib/communication/DY.Lib.Communication.Core.Invariants.fst
- src/lib/communication/DY.Lib.Communication.Core.Lemmas.fst
- src/lib/communication/DY.Lib.Communication.Core.Properties.fst
- src/lib/communication/DY.Lib.Communication.RequestResponse.Invariants.fst
- src/lib/communication/DY.Lib.Communication.RequestResponse.Lemmas.fst
- src/lib/communication/DY.Lib.Communication.RequestResponse.fst
- src/lib/comparse/DY.Lib.Comparse.DYUtils.fst
The primary role of this PR is to change confidential messages (and the requests that they are built on), so that the receiver of a confidential message/request gets a simpler, more obvious guarantee --- that a request/confidential message has indeed been received.
The lemma `conf_message_secrecy` in DY.Lib.Communication.Core.Properties.fst allows us to dig into the event predicates, and extract the most relevant information. This may be further improveable, for instance by strengthening the predicate for `CommConfReceiveMsg` (e.g., to say that the payload parses successfully). See for comparison the predicate for request received events, which contains many of the desired guarantees already, only needing to refer to the send event for guarantees that depend on the higher layer send …
> Adjust request/confidential message postconditions

- src/lib/communication/DY.Lib.Communication.Core.Lemmas.fst
- src/lib/communication/DY.Lib.Communication.Core.fst
- src/lib/communication/DY.Lib.Communication.RequestResponse.Lemmas.fst
- src/lib/communication/DY.Lib.Communication.RequestResponse.fst
This PR has two main components:
- First, to make most of the communication layer opaque to the SMT solver, so that when we reason about the behaviour of the communication functions, we only get the information included in their specification lemmas, not the full details of how everything is computed.
- Second, adding SMT patterns to the communication layer core, as for the request response lemmas, so that they can be automatically triggered in the right circumstances.
I've also cleaned up end-of-line spaces as encountered, but this isn't a semantic change.
As of right now, all of the user-facing core functions are successfully opaque, as are most of the other core functions, but I haven't been able to make `verify_message` opaque without breaking proofs, even when revealing it. I think …
> Improve proof performance by making communication layer functions opaque and relying on lemmas

- src/lib/comparse/DY.Lib.Comparse.Glue.fst
This PR introduces more SMT patterns, with a switch to enable them (I am not sure how aggressive they are).
In examples we can do `let _ = enable_comparse_wf_lemmas_smtpats` to enable the switch globally, this could help simplify examples but I did not do it (this can be discussed).
> feat: add SMT patterns for Comparse, with a switch

- examples/iso_dh/DY.Example.DH.Protocol.Stateful.Proof.fst
- examples/nsl_pk/DY.Example.NSL.Protocol.Stateful.Proof.fst
- src/lib/event/DY.Lib.Event.Typed.fst
- src/lib/state/DY.Lib.State.Map.fst
- src/lib/state/DY.Lib.State.PKI.fst
- src/lib/state/DY.Lib.State.PrivateKeys.fst
- src/lib/state/DY.Lib.State.Typed.fst
- src/lib/utils/DY.Lib.SplitFunction.fst
Fixes #37.
This uses an approach similar to #40 with `unfold`s, but is less aggressive in the unfolding hence I am confident this scales well (contrary to #40 whose unfolded SMT patterns could grow big).
The reason we have a lot of boilerplate in the examples is that although we prove `has_local_bytes_state_predicate pki_tag_and_invariant` (post-condition of `mk_state_pred_correct`), the SMT patterns are on `has_pki_invariant`, which although equivalent is not the same term, hence are different with respect to SMT patterns.
To solve this problem, the idea is that `has_..._state_predicate` now unfolds to `has_local_bytes_state_predicate tag_and_pred`, where `tag_and_pred` is specific to the state we are currently dealing with. It's nice for two reasons:
- `tag_and_pred` is not unfolded, …
> cleanup: reduce boilerplate to merge local predicates

- src/core/DY.Core.Attacker.Knowledge.Kleene.fst
- src/core/DY.Core.Attacker.Knowledge.fst
While trying to explain why we define `attacker_knows` as we do, I realized we could argue that it is a Kleene fixpoint. This PR makes this more explicit.
Furthermore:
- We prove the attacker knowledge is the weakest predicate that obeys the attacker rules, this gives to a very nice proof of the attacker knowledge: because `is_publishable` also obeys the attacker rules, it must be stronger than `attacker_knows` (because it is the weakest such predicate).
- We prove that the attacker knowledge is preserved by computing cryptographic functions, these lemmas are currently missing. I think this additional proofs explain why the diff is positive. This paves the way to formally define the attacker API, which we didn't take the time to write properly yet.
> feat: define attacker knowledge as a Kleene fixpoint
